### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by haizaar** [pohmelie/ainject#1]
Good day,

How about pypi release?

Thanks in advance!

**Comment by pohmelie** [comment]
Released, but package is «broken» a little, since requires setuptools >= 30.3.0 for installation.

**Comment by haizaar** [comment]
Thanks!

Why do you say it's "broken"? setuptools 30.3.0 was released in Dec 2016...

**Comment by pohmelie** [comment]
@haizaar 
The reason of calling this «broken» is that upstream python 3.6 offered with setuptools 28.8.0, and user need extra movements to upgrade setuptools with pip. This is easy, but annoying.
